version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    hostname: zookeeper
    networks:
      - streaming

  kafka:
    image: confluentinc/cp-kafka:3.3.0
    hostname: kafka
    networks:
      - streaming
    depends_on:
      - zookeeper

  kafka-rest:
    image: confluentinc/cp-kakfa-rest:3.3.0
    hostname: kafka-rest
    networks:
      - streaming
    depends_on:
      - zookeeper
      - kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:3.3.0
    hostname: schema-registry
    networks:
      - streaming
    depends_on:
      - zookeeper
      - kafka

  ps-collector:
    image: ucalgary/ps-stream
    command:
      - collect
    networks:
      - streaming

  ps-publisher:
    image: ucalgary/ps-stream
    command:
      - publish
    networks:
      - streaming

  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.8.2
    environment:
      - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
      - PROXY=true
    networks:
      - streaming

networks:
  streaming:
